### PR TITLE
Make sure our bindings pass the C library's tests

### PR DESCRIPTION
**Pull request by Michael-F-Bryan**
It'd be nice to make sure our bindings don't accidentally break things. 

The underlying C library already has several tests for functionality, so we can take advantage of their hard work by porting the tests to Rust and making sure everything still passes.

### CODE REVIEW

**Comment by shekohex** [comment]
I will try to help Porting more tests to make sure that everything is going well.

**Comment by Michael-F-Bryan** [comment]
Thanks @shekohex. I've added you as a collaborator, so now you can merge PRs and have commit access.

**Comment by Michael-F-Bryan** [comment]
I might need to remove that hkdf test. I committed it because when running the test I was getting a crash due to an illegal instruction and thought we might have messed the crypto code up really badly. 

On further inspection it looks like we encountered an `unimplemented!()` and because panicking into C is undefined behaviour, it was translated into a hard abort. For some reason the stable travis build was able to unwind the stack just fine, because it shows `thread 'test_hkdf_vector_v2' panicked at 'not yet implemented', libsignal-protocol/src/crypto.rs:94:9`.

@shekohex do you think it's worth us implementing more of the `DefaultCrypto` at the moment, or would our efforts be better spent working on other things? One of my major goals is implementing the full [Building a Session][bas] example, because once we get to that point we're able to start on a high-level `libsignal-service` crate.

[bas]: https://github.com/signalapp/libsignal-protocol-c#building-a-session

**Comment by shekohex** [comment]
> do you think it's worth us implementing more of the DefaultCrypto at the moment?

I have no problem, maybe today i would start on implementing the `DefaultCrypto` using pure rust implementations from other crates, i think it would also mark that task as finished.
and in my opinion we are going to implement it any way.

**Pull request merged**
