### PR TITLE
Dependency update

### LINKED ISSUE #55: Consider removing Cargo.lock
[The Rust FAQ seems to recommend](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) to *not* check in `Cargo.lock` in library projects.

Either way, with your permission, I'll send in a PR with dependency updates, because in my end-application I find quite a few duplicated dependencies by now :-)

### PR DESCRIPTION
**Pull request by rubdos**
Updates dependencies and fixes #55 

Feel free to cherry-pick 4755218 if you'd rather keep `Cargo.lock`!

### CODE REVIEW

**Comment by rubdos** [comment]
It looks like a transitive dependency uses `ptr_cast`, which is [stabilized in 1.38](https://github.com/rust-lang/rust/pull/62713). Should the minimum Rust version be pushed up?

**Comment by Michael-F-Bryan** [comment]
I think we're at Rust 1.43.1 at the moment, so bumping the MSRV to 1.38 is fair enough.

Make sure you update [this comment](https://github.com/Michael-F-Bryan/libsignal-protocol-rs/blob/bc0d07bec5fd8e853973cdd187ca0d3d7c2618c4/.travis.yml#L41) noting which feature our MSRV depends on.

**Comment by Michael-F-Bryan** [comment]
Would you be able to do a `git submodule update --remote` while you're at it? It looks like they did [a small bugfix](https://github.com/signalapp/libsignal-protocol-c/commit/71954c53860b83e358c9d8c4898d003f16ace375) to stop a leak. When the PR lands I'll make a new `libsignal-protocol-sys` release so the fixed code is on GitHub.

**Comment by rubdos** [comment]
Melded the Rust update in the dependency update (since those go hand-in-hand), added a bump to libsignal-c in a separate commit.

**Pull request merged**
