### PR TITLE
[WIP] Implementing Crypto using Pure rust at `crypto-native` feature

### PR DESCRIPTION
**Pull request by shekohex**
I did not know where i can find a best crate for the `encryption` and `decryption` for the `aes`.

Signed-off-by: Shady Khalifa <shekohex@gmail.com>

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
Regarding the AES code, could we use either the [aes](https://docs.rs/aes/0.3.2/aes/) or [aes-soft](https://docs.rs/aes-soft/0.3.3/aes_soft/) crate? 

In particular, the `aes-soft` crate seems to implement everything in software and has minimal dependencies (`byteorder`, `opaque-debug`, and `block-cipher-trait`), so I'd lean towards that one. For the `native` cargo feature, I think we'd want to aim for fast compile times and minimal reliance on native libraries or platform-specific code.

**Comment by shekohex** [comment]
the problem about `aes`-soft, that i don't understand what types of `Aes{SIZE}` that crate [`aes`](https://docs.rs/aes/0.3.2/aes/) seems to have, since we have to implement that for different types of `CTR` and `CBC` with different sizes.
but either of these seems to have the `CBC` nor `CTR`, i'm a bit confused, since all of them has no type post-fixes as it was in the `openssl`, any clarification here ? i'm a bit lost here :face_with_head_bandage:

> by the way: `aes` says:
   This crate is a wrapper around different implementations of AES block ciphers.
    Currently it uses:
      * `aes-soft` hardware independent bit-sliced implementation
      * `aesni` implementation using AES-NI instruction set. Used for x86-64 and x86 target architectures with enabled aes and sse2 target features (the latter is usually enabled by default).
   Crate switches between implementations automatically at compile time. (i.e. it does not use run-time feature detection)

**Comment by Michael-F-Bryan** [comment]
To be honest, I'm not 100% sure what the difference between CTR and CBC is, or how it interacts with the `aes` crate, but... what if we play dumb and ignore the CTR/CBC argument for now? 

We can always merge an initial implementation and rewrite the encryption/decryption at a later date.

**Comment by shekohex** [comment]
Ok, i would recommend marking this PR as initial PR for the `crypto-native` until i find a proper answer for that https://github.com/Michael-F-Bryan/libsignal-protocol-rs/pull/22#issuecomment-494076198

Until then, we will keep that branch `crypto-native`

**Pull request merged**
