### PR TITLE
Mark `signal_buffer` struct as thread-safe

### PR DESCRIPTION
**Pull request by ntninja**
See explanation in source comment for why I believe this is OK.

### CODE REVIEW

**Comment by rubdos** [comment]
Do we know whether it's safe to `drop()` from a different thread than were it was created?

**Comment by gferon** [comment]
> Do we know whether it's safe to `drop()` from a different thread than were it was created?

AFAIK, allocators are thread-safe, so it shouldn't be a problem at all.

**Review by gferon — APPROVED** [review]

**Comment by rubdos** [comment]
> > Do we know whether it's safe to `drop()` from a different thread than were it was created?
> 
> AFAIK, allocators are thread-safe, so it shouldn't be a problem at all.
> 
> EDIT: as long as we don't delete anything in Rust that was allocated in FFI zipper_mouth_face

Rust allocators may be thread safe, but Buffer is initialized by `libsignal-protcool-c`, so may as well be unsafe. Additionally, the destructor also runs in C afaik.

**Comment by ntninja** [comment]
`malloc`/`free` are required to be thread-safe since C11: https://en.cppreference.com/w/c/memory/free

As to whether deallocating a `malloc`'d pointer on another thread is valid, I could only find anecdotal evidence of people successfully doing this in practice:
https://stackoverflow.com/q/15995831/277882 (for C)
https://stackoverflow.com/q/2363888/277882 (for Windows C++)

There is no mentioning of this in either C or C++ standards however, so it appears to be something that “works in practice” even though its not explicitly mentioned anywhere. I'm also pretty sure I would have found lots of whining about whatever platform didn't support this, if there was one.

**Comment by rubdos** [comment]
```C
void signal_buffer_free(signal_buffer *buffer)
{
    if(buffer) {
        free(buffer);
    }
}
```

Since that's the only thing that happens, I suppose it's all safe. However, I cannot really find something about thread safety in `libsignal-protocol-c` at all, but it seems to be locking most primitives anyhow. Let's get this in then :-)

**Pull request merged**
