### PR TITLE
[ci]: Add `rustfmt` roles, and ci checks for `rustfmt` and `clippy`

### PR DESCRIPTION
**Pull request by shekohex**
Hello @Michael-F-Bryan, this is a small contribution, adding some formatting roles and also some ci checks.

I would help to improve this project, so please let me know how to connect with you via email or though twitter.

Signed-off-by: Shady Khalifa <shekohex@gmail.com>

### CODE REVIEW

**Comment by shekohex** [comment]
Yeah, it of course would fail because we need format the project with the new roles, also we need to till clippy to ignore the `-sys` crate.

**Comment by Michael-F-Bryan** [comment]
> Yeah, it of course would fail because we need format the project with the new roles, also we need to till clippy to ignore the -sys crate.

Could we just add `#![allow(clippy::all)]` to the `-sys` crate?

**Comment by shekohex** [comment]
Yes, i think that would solve the `-sys` crate issue, also the `rustfmt.toml` needs `nightly` toolchain, i will update that PR today.

**Comment by shekohex** [comment]
good, no it fails because we need to commit the roles, i guess if i did that in the same PR, that would be a huge PR, so i will Open a new PR with these fixes and then we back to that PR

**Comment by shekohex** [comment]
OK, i created #4 and #3 , i think #4  should be first then #3 ?

**Comment by Michael-F-Bryan** [comment]
By the looks of things, the only reason #4 is massive is because we set ` tab_spaces = 2` and then the entire crate gets re-formatted. Rust [prefers to indent with 4 spaces][style-guide], so is there a particular reason why you chose to indent with 2 spaces?

I don't mind if the diff gets a bit big due to formatting changes, it's probably more important to keep all formatting/lint related changes in a single PR so they're all logically kept together.

[style-guide]: https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/guide.md#indentation-and-line-width

**Comment by shekohex** [comment]
> so is there a particular reason why you chose to indent with 2 spaces?

Oh, actually i think it's just me, i think the 2 spaces takes small amount of my small screen, but, i think we should use 4 instead as that is the standard for all rust developers and most IDEs.

**Comment by shekohex** [comment]
@Michael-F-Bryan i think the `rustfmt` is now very good, can we push that now ?

**Pull request merged**
